// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqlkrnlehiwzrztkpzzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbGtybmxlaGl3enJ6dGtwenprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDc5MjcsImV4cCI6MjA2MDEyMzkyN30.WKdk5RW8mpVaDR0sdNYjG8g4e1PkG84MKMd9WWDX4C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);